version: "2"

checks:
  method-complexity:
    config:
      threshold: 9

engines:
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true

ratings:
  paths:
    - src/**.php

exclude_paths:
  - test/**/*
