name: Codes Quality

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    paths:
      - .github/workflows/codes.yml
      - src/*
      - test/*
  schedule:
    - cron: '0 0 1 * *'

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
  CC_TEST_REPORTER_URL: https://codeclimate.com/downloads/test-reporter/test-reporter-0.7.0-linux-amd64

jobs:
  analyze:
    name: Static Analysis
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: phpstan, cs2pr
        coverage: none

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.composer/cache
        key: php-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: php-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Static Analysis
      run: phpstan analyse src --level 6 --no-progress --error-format=checkstyle | cs2pr

  tests:
    name: Test - PHP ${{ matrix.php-version }}
    runs-on: ubuntu-20.04
    needs: analyze
    env:
      GIT_COMMIT_SHA: ${{ github.sha }}
      GIT_BRANCH: ${{ github.ref }}

    strategy:
      matrix:
        php-version: ['7.2', '7.3', '7.4', '8.0', '8.1']

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: xdebug
        tools: composer

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.composer/cache
        key: php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: php-${{ matrix.php-version }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables
    # https://github.com/deivid-rodriguez/pry-byebug/blob/377e5b7d229a157bb896f21d776f71fc389a5c00/.github/workflows/ubuntu.yml#L46-L57
    - name: Set ENV for CodeClimate (pull_request)
      if: github.event_name == 'pull_request'
      run: echo "GIT_BRANCH=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

    - name: Spec
      run: composer spec

    - name: CodeClimate
      env:
        LCOV_REPORT: ${{ github.workspace }}/test/lcov.info
        CODECLIMATE_REPORT: ${{ github.workspace }}/test/codeclimate.${{ matrix.php-version }}.json
      run: |
        curl -LSs $CC_TEST_REPORTER_URL > ./cc-test-reporter && chmod +x ./cc-test-reporter
        ./cc-test-reporter format-coverage -t lcov -o $CODECLIMATE_REPORT $LCOV_REPORT

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: test/lcov.info
        parallel: true

    - name: Save Coverage Reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: ${{ github.workspace }}/test/*.json

  reports:
    name: Reports
    needs: tests
    runs-on: ubuntu-20.04

    steps:
    - name: Download Reports
      uses: actions/download-artifact@v2
      with:
        name: test-reports

    - name: Coveralls Report
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: test/lcov.info
        parallel-finished: true

    - name: CodeClimate Report
      run: |
        curl -LSs $CC_TEST_REPORTER_URL > ./cc-test-reporter && chmod +x ./cc-test-reporter
        ./cc-test-reporter sum-coverage -o - codeclimate.*.json | ./cc-test-reporter upload-coverage --input -
