name: Prepare

on:
  pull_request_target:
    branches: [main]
    paths:
      - composer.*
      - src/*
      - tests/*

env:
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

jobs:
  prepare:
    name: Prepare
    uses: projek-xyz/actions/.github/workflows/configure.yml@main
    secrets: inherit
