name: Tests

on:
  pull_request:
    branches:
      - master
    # paths:
    #   - src/*
    #   - test/*
  push:
    branches:
      - master
    # paths:
    #   - src/*
    #   - test/*

jobs:
  test:
    name: Runs on PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.1', '7.2', '7.3', '7.4']

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: xdebug

    - name: Get Composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache Composer dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Spec
      run: composer spec

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: test/lcov.info
        flag-name: run-php-${{ matrix.php-versions }}
        parallel: true

  finish:
    name: Reports
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: test/lcov.info
        parallel-finished: true
